on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TAGS=latest" >> $GITHUB_ENV
          else
            echo "TAGS=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/rdoy-lab/hello-app:${{ env.TAGS }}, ghcr.io/rdoy-lab/hello-app:${{ github.sha }}
